#!/usr/bin/env bash
# installs nginx and configures it on a remote server

apt-get update -y
apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "Hello World!" > /var/www/html/index.html'
service nginx restart


